version: "3.3"

services:
  traefik:
    image: "traefik:v2.4.5"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-service:
    image: traefik/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`localhost`)"
      - "traefik.http.routers.my-router.entrypoints=web"
      # Adds redirect scheme middleware
      - "traefik.http.routers.my-router.middlewares=my-redirect"
      # Redirects requests to https.
      - "traefik.http.middlewares.my-redirect.redirectscheme.scheme=https"
      # Applies a permanent redirection.
      - "traefik.http.middlewares.my-redirect.redirectscheme.permanent=true"