version: "3.3"

services:
  traefik:
    image: "traefik:v2.4.5"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-service:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`localhost`)"
      - "traefik.http.routers.my-router.entrypoints=web"
      # Adds replace path regex middleware
      - "traefik.http.routers.my-router.middlewares=my-path"
      # Replaces the path 'mert/' with 'traefik/'
      - "traefik.http.middlewares.my-path.replacepathregex.regex=^/mert/(.*)"
      - "traefik.http.middlewares.my-path.replacepathregex.replacement=/traefik/$$1"